"""Reference implementation of the timestamp rules **as this port implements them**.

`tests/fixtures/logit_filters.json` carries three expectation sets for
`ApplyTimestampRules`, because there are three distinct behaviours in play:

* `timestamp_rules` — what `mlx_whisper` 0.4.3 actually does. Generated by
  driving upstream's own `D.ApplyTimestampRules` in `gen_fixtures.py`.
* `timestamp_rules_openai_semantics` — what `openai/whisper` does. Generated by
  the reimplementation in `gen_fixtures.py`.
* `timestamp_rules_port_semantics` — what this crate does, and the only set the
  Rust tests assert against. Generated here.

The port is a deliberate hybrid of the two, documented in `PARITY.md`:

* **`DEC-1`, from `mlx_whisper`** — the final "sample a timestamp if their total
  probability beats every text token" rule normalises the logits *as they
  arrived*, carrying only `SuppressBlank`/`SuppressTokens`, not this filter's
  own mask. `openai/whisper` mutates its `logits` tensor in place, so by the
  time it takes the `log_softmax` the mask is already folded in; `mlx_whisper`
  accumulates a separate `mask` array and normalises the untouched `logits`.
  This crate follows `mlx_whisper`, which is the package it ports.
* **`DEC-2`, from `openai/whisper`** — the monotonicity clause collects token
  *values* with `>=`, not list *indices* with `>`. `mlx_whisper`'s version
  yields positions within `seq` rather than token ids, so its mask slice
  `[timestamp_begin : last_timestamp]` is empty and the "timestamps shouldn't
  decrease" constraint never fires at all. This crate follows `openai/whisper`,
  because bug-for-bug parity there would mean shipping a documented constraint
  that does nothing.

Kept in its own numpy-only module — no `mlx` import — so that it can be
exercised without a working `mlx` install, and so `gen_fixtures.py` and any
offline regeneration share a single implementation that cannot drift.
"""

import numpy as np


def ranges(idx):
    """Compress a sorted index array into `[start, end_inclusive]` pairs."""
    out = []
    idx = np.asarray(idx)
    if idx.size == 0:
        return out
    start = prev = int(idx[0])
    for v in map(int, idx[1:]):
        if v == prev + 1:
            prev = v
            continue
        out.append([start, prev])
        start = prev = v
    out.append([start, prev])
    return out


def _logsumexp(x):
    m = x.max()
    if not np.isfinite(m):
        return m
    return np.float32(m + np.log(np.exp(np.float64(x) - np.float64(m)).sum()))


def port_rules(toks, cap, logits, *, sample_begin, ts_begin, eot, no_timestamps):
    """Apply this port's `ApplyTimestampRules` to every row of `logits`.

    Mirrors `src/decoding.rs::apply_timestamp_rules` clause for clause. Returns
    the filtered array (`logits + mask`), same shape as `logits`.
    """
    logits = np.asarray(logits, dtype=np.float32)
    mask = np.zeros(logits.shape, np.float32)
    n_vocab = logits.shape[1]

    mask[:, no_timestamps] = -np.inf

    seq = list(toks[sample_begin:])
    last_was_timestamp = len(seq) >= 1 and seq[-1] >= ts_begin
    penultimate_was_timestamp = len(seq) < 2 or seq[-2] >= ts_begin

    for k in range(logits.shape[0]):
        if last_was_timestamp:
            if penultimate_was_timestamp:  # two in a row -> next must be text
                mask[k, ts_begin:] = -np.inf
            else:  # a lone timestamp -> next must not be ordinary text
                mask[k, :eot] = -np.inf

        # DEC-2: token *values*, `>=` — openai/whisper's selection, so
        # `<|0.00|>` (== ts_begin) counts.
        timestamps = [v for v in seq if v >= ts_begin]
        if timestamps:
            if last_was_timestamp and not penultimate_was_timestamp:
                timestamp_last = timestamps[-1]
            else:
                timestamp_last = timestamps[-1] + 1
            mask[k, ts_begin : min(timestamp_last, n_vocab)] = -np.inf

    if len(toks) == sample_begin:
        mask[:, :ts_begin] = -np.inf
        if cap is not None:
            mask[:, ts_begin + cap + 1 :] = -np.inf

    # DEC-1: normalise the **unmasked** logits, as mlx_whisper does.
    for k in range(logits.shape[0]):
        row = logits[k]
        logprobs = row - _logsumexp(row)
        t_lp = _logsumexp(logprobs[ts_begin:])
        x_lp = logprobs[:ts_begin].max()
        if t_lp > x_lp:
            mask[k, :ts_begin] = -np.inf

    return logits + mask


def port_semantics_cases(cases, logits, row_labels, **kw):
    """Build the `timestamp_rules_port_semantics` section of the fixture."""
    out = {}
    for name, (toks, cap) in cases.items():
        r = port_rules(toks, cap, logits, **kw)
        rows = []
        for i in range(r.shape[0]):
            row = r[i]
            neg = np.flatnonzero(np.isneginf(row)).astype(np.int64)
            finite = row[np.isfinite(row)]
            rows.append(
                {
                    "row": i,
                    "label": row_labels[i],
                    "n_suppressed": int(neg.size),
                    "suppressed_ranges": ranges(neg),
                    "finite_count": int(finite.size),
                    "finite_sum": float(np.float64(finite).sum()),
                }
            )
        out[name] = {
            "tokens": list(toks),
            "max_initial_timestamp_index": cap,
            "rows": rows,
        }
    return out
